name: dct
favicon: null
layout_spectrum: 0.09110788349062204
typography_spectrum: 0.8286346618551761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5547091034241021
  lightness: 0.3145448383875191
  saturation: 0.8295664223842323
  rhythmicContrast: 0.6252702630590647
purpose: []
